#!/bin/bash

# Professor GENIE Chrome Extension - Asset Creation Script
# This script helps organize the asset creation process for Chrome Web Store submission

echo "🎓 Professor GENIE Chrome Extension - Asset Creation Helper"
echo "============================================================"

# Create directories for assets
echo "📁 Creating asset directories..."
mkdir -p "store-assets/icons"
mkdir -p "store-assets/screenshots"  
mkdir -p "store-assets/promotional"
mkdir -p "store-assets/marketing"

echo "✅ Directory structure created:"
echo "   store-assets/"
echo "   ├── icons/"
echo "   ├── screenshots/"
echo "   ├── promotional/"
echo "   └── marketing/"
echo ""

# Icon creation checklist
echo "🎨 ICON CREATION CHECKLIST"
echo "=========================="
echo "Required PNG files with transparent backgrounds:"
echo ""
echo "📐 Extension Icons (for manifest.json):"
echo "   ☐ icon16.png  (16x16px)   - Toolbar icon"
echo "   ☐ icon48.png  (48x48px)   - Extensions page" 
echo "   ☐ icon128.png (128x128px) - Web Store listing"
echo ""
echo "🎨 Design Requirements:"
echo "   • Graduation cap as primary element"
echo "   • Professor GENIE blue theme (#2563eb)"
echo "   • Professional academic appearance"
echo "   • Clear visibility at smallest size (16px)"
echo "   • Consistent branding across all sizes"
echo ""

# Screenshot requirements
echo "📸 SCREENSHOT REQUIREMENTS"
echo "=========================="
echo "Required: 1280x800px PNG format"
echo ""
echo "   ☐ screenshot1.png - Extension on Canvas LMS"
echo "      • Show Professor GENIE overlay panel"
echo "      • Highlight Extract → Generate → Apply → Submit workflow"
echo "      • Include actual LMS interface in background"
echo ""
echo "   ☐ screenshot2.png - Options/Settings page"
echo "      • Display domain configuration interface"
echo "      • Show security features"
echo "      • Highlight universal LMS compatibility"
echo ""
echo "   ☐ screenshot3.png (optional) - Different LMS platform"
echo "      • Show extension working on Moodle or D2L"
echo "      • Demonstrate universal compatibility"
echo ""

# Promotional assets
echo "🚀 PROMOTIONAL ASSETS"
echo "===================="
echo "   ☐ promotional-tile.png (440x280px) - Featured placement"
echo "   ☐ store-banner.png (1400x560px) - Optional banner"
echo ""

# AI Generation prompts
echo "🤖 AI GENERATION PROMPTS"
echo "========================"
echo ""
echo "For Icons:"
echo "'Professional graduation cap icon for Professor GENIE AI teaching"
echo "assistant, modern flat design, blue gradient #2563eb to #764ba2,"
echo "subtle tech elements, academic theme, clean minimal, transparent"
echo "background, suitable for Chrome extension'"
echo ""
echo "For Screenshots:"
echo "'Chrome extension interface screenshot, Professor GENIE overlay"
echo "on Canvas LMS, professional blue UI, grading workflow, academic"
echo "software, clean modern design, 1280x800 resolution'"
echo ""

# Tools recommendation
echo "🛠️  RECOMMENDED TOOLS"
echo "===================="
echo "Professional: Figma, Adobe Illustrator, Sketch"
echo "Free Options: GIMP, Inkscape, Canva Free"
echo "AI Generation: Midjourney, DALL-E, Stable Diffusion"
echo "Screenshots: Browser developer tools, Snagit, Lightshot"
echo ""

# File organization
echo "📋 FILE ORGANIZATION"
echo "===================="
echo "Once created, organize files as:"
echo ""
echo "extensions/lms-integration/"
echo "├── icons/"
echo "│   ├── icon16.png"
echo "│   ├── icon48.png"
echo "│   └── icon128.png"
echo "└── store-assets/"
echo "    ├── screenshots/"
echo "    │   ├── screenshot1.png"
echo "    │   ├── screenshot2.png"
echo "    │   └── screenshot3.png"
echo "    └── promotional/"
echo "        ├── promotional-tile.png"
echo "        └── store-banner.png"
echo ""

# Quality checklist
echo "✅ QUALITY CHECKLIST"
echo "===================="
echo "Before submission, verify:"
echo "   ☐ All icons have transparent backgrounds"
echo "   ☐ Icons are clearly visible at 16px size"
echo "   ☐ Consistent Professor GENIE branding"
echo "   ☐ High resolution and crisp edges"
echo "   ☐ Professional academic appearance"
echo "   ☐ Screenshots show actual extension functionality"
echo "   ☐ All required dimensions are correct"
echo "   ☐ Files are properly named and formatted"
echo ""

echo "🎯 NEXT STEPS"
echo "============="
echo "1. Create icons using design tool or AI generation"
echo "2. Take screenshots of extension in real LMS environments"
echo "3. Replace placeholder files with actual assets"
echo "4. Review CHROME_WEB_STORE_SUBMISSION.md for full process"
echo "5. Zip extension files for Chrome Web Store upload"
echo ""

echo "🌟 Your Professor GENIE extension is ready for the Chrome Web Store!"
echo "Visit the Chrome Web Store Developer Dashboard to begin submission."
echo ""